#!/usr/bin/env bash

: "${FZ:=fzy}"
: "${DB:="${XDG_DATA_HOME:-$HOME/.local/share}/tea.db"}"

function die {
    echo "$@"
    exit 1
}

function escape_sqlite {
    sed "s/'/''/g" <<< "$1"
}

function escape_or_null {
    if [ -n "$1" ]; then
    echo "'$(escape_sqlite "$1")'"
    else
    echo NULL
    fi
}

function new_tea {
    read -r -p "Name: " name
    read -r -p "Amount: " amount
    read -r -p "URL: " url
    read -r -p "Type: " typ
    read -r -e -i "$(date +%Y)" -p "Year: " year

    [ -z "$name" ] && die "Please supply a name"
    name="'$(escape_sqlite "$name")'"

    amount="$(escape_or_null "$amount")"
    url="$(escape_or_null "$url")"
    typ="$(escape_or_null "$typ")"
    year="$(escape_or_null "$year")"
    uid="$(uuidgen)"

    sqlite3 "$DB" << SQL
    insert into teas (name, year, amount, type, url, uid)
    values ($name, $year, $amount, $typ, $url, '$uid');
SQL
    
}

function _drink_tea {
    tea=$1
    uid="$(uuidgen)"
    read -r -p "Amount: " amount

    echo "New entry: $uid"

    sqlite3 "$DB" << SQL
        insert into log (tea, amount, date, notes, uid)
        values ('$(escape_sqlite "$tea")', $(escape_or_null "$amount"), date('now'), NULL, '$uid');
SQL
    
    if tmpfile=$(mktemp -q /tmp/teanotes.XXXXX); then
        [ -z "$EDITOR" ] && die "NO \$EDITOR set."
        $EDITOR "$tmpfile"
        notes="$(cat "$tmpfile")"
        sqlite3 "$DB" << SQL
            update log set notes = '$(escape_sqlite "$notes")' where uid = '$uid';
SQL

    else
        die "$0: Couldn't create tempfile"
    fi
}

function drink_tea_fzy {
    tea="$(list_teas)"
    [ -z "$tea" ] && exit 0
    _drink_tea "$tea"

}

function list_teas {
    sqlite3 "$DB" "select name from teas" | $FZ
}

function edit_notes {
    uid="$1"
    if [ -z "$uid" ]; then
        echo "No uid given; using latest entry"
        uid="$(sqlite3 "$DB" 'select uid from log order by date desc limit 1')"
    else
        uid="$(sqlite3 "$DB" "select uid from log where uid like '$(escape_sqlite "$uid")%'")"
        [ -z "$uid" ] && die "Couldn't find a log entry with that uid."
    fi
    
    if tmpfile=$(mktemp -q /tmp/teanotes.XXXXX); then
        [ -z "$EDITOR" ] && die "NO \$EDITOR set."
        sqlite3 "$DB" "select notes from log where uid = '$(escape_sqlite "$uid")'" > $tmpfile
        $EDITOR "$tmpfile"
        notes="$(cat "$tmpfile")"
        sqlite3 "$DB" << SQL
            update log set notes = '$(escape_sqlite "$notes")' where uid = '$uid';
SQL
    else
        die "$0: Couldn't create tempfile"
    fi
}

function quick_log {
    sqlite3 "$DB" "select tea, date, uid from log order by date desc limit 10"
}

[ -f "$DB" ] || sqlite3 "$DB" << SQL
    create table teas (
    name,
    amount,
    url,
    type,
    year,
    uid
    );

    create table log (
    tea,
    amount,
    date,
    notes,
    uid
    );
SQL


case "$1" in
    new)
    new_tea
    ;;
    list)
    list_teas
    ;;
    edit)
    edit_notes "$2"
    ;;
    lg)
    quick_log
    ;;
    *)
    drink_tea_fzy
    ;;
esac
